// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  sidebar: [
    {
      type: "category",
      label: "GET STARTED",
      collapsible: false,
      items: [
        {
          type: "link",
          href: "/get-started/Overview",
          label: "Overview",
        },
        {
          type: "link",
          href: "/get-started/Quickstart",
          label: "Quickstart",
        },
        {
          type: "link",
          href: "/get-started/Models",
          label: "Models",
        },
      ],
    },
    {
      type: "html",
      value: '<div class="sidebar-divider"></div>',
      defaultStyle: true,
    },
    {
      type: "category",
      label: "CAPABILITIES",
      items: [
        {
          type: "autogenerated",
          dirName: "Autogenerate/tutorial-extras",
        },
      ],
    },
  ],
};

export default sidebars;
