// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  sidebar: [
    // Manual items at the top
    // {
    //   type: "html",
    //   value: '<p class="sidebar-text">Docs of Zero</p>',
    //   defaultStyle: true,
    // },
    {
      type: "html",
      value: '<div class="sidebar-divider"></div>',
      defaultStyle: true,
    },
    {
      type: "doc",
      id: "index",
      label: "North of Zero",
    },
    {
      type: "category",
      label: "Getting Started",
      items: [
        {
          type: "link",
          label: "Google",
          href: "https://google.com",
        },
      ],
    },
    {
      type: "category",
      label: "Core Concepts",
      items: [
        {
          type: "link",
          label: "Google",
          href: "https://google.com",
        },
      ],
    },
    {
      type: "html",
      value: '<div class="sidebar-divider"></div>',
      defaultStyle: true,
    },
    // Auto-generated items for the rest of the docs
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
};

export default sidebars;
