// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  sidebar: [
    {
      type: "category",
      label: "OVERVIEW",
      collapsible: false,
      className: "modifier-header",
      items: [
        {
          type: "link",
          href: "/",
          label: "Disclaimer",
        },
        {
          type: "link",
          href: "https://perks.northofzero.dev/",
          label: "Perks",
        },
        {
          type: "link",
          href: "https://www.northofzero.dev/offer",
          label: "45min Consultation",
        },
      ],
    },
    {
      type: "html",
      value: '<div class="sidebar-divider"></div>',
      defaultStyle: true,
    },
    {
      type: "category",
      label: "PLAYBOOKS",
      collapsible: false,
      className: "modifier-header",
      items: [
        {
          type: "autogenerated",
          dirName: ".",
        },
      ],
    },
  ],
};

export default sidebars;
